name = "noteask-api"
main = "core/worker.ts"
compatibility_date = "2024-02-19"
compatibility_flags = ["nodejs_compat"]

[placement]
mode = "smart"

# ------------------------------------------------------------------------------------------------------------

[env.local.vars]
WORKER_ENV = "development"
WEB_BASE_URL = "https://localhost:4000/"
LEMONSQUEEZY_STORE_ID = 71160
LEMONSQUEEZY_PERSONAL_LIFETIME_ACCESS_VARIANT_ID = 258991
LEMONSQUEEZY_TEAM_LIFETIME_ACCESS_VARIANT_ID = 258993
POSTHOG_HOST = "https://us.posthog.com"
POSTHOG_API_KEY = "phc_xV2WQPwoKEeuntgAvOBmfCnapTg7F0PIXTWGNKqpBzf"
SUPPORT_EMAIL = "dinsterizer@gmail.com"
CLERK_PUBLISHABLE_KEY = "pk_test_Y2hpZWYtY29sdC05OC5jbGVyay5hY2NvdW50cy5kZXYk"


[[env.local.r2_buckets]]
binding = 'PUBLIC_BUCKET'
bucket_name = 'noteask-public-local'

# ------------------------------------------------------------------------------------------------------------

[env.preview.route]
pattern = "preview.api.noteask.com"
custom_domain = true

[env.preview.vars]
WORKER_ENV = "development"
WEB_BASE_URL = "https://preview.app.noteask.com/"
LEMONSQUEEZY_STORE_ID = 71157
LEMONSQUEEZY_PERSONAL_LIFETIME_ACCESS_VARIANT_ID = 258985
LEMONSQUEEZY_TEAM_LIFETIME_ACCESS_VARIANT_ID = 258986
POSTHOG_HOST = "https://us.posthog.com"
POSTHOG_API_KEY = "phc_QmK2BtdmITfPpNviFvKXfrifO4kCwJe1bXX2VwyUwwc"
SUPPORT_EMAIL = "dinsterizer@gmail.com"
CLERK_PUBLISHABLE_KEY = "pk_test_Y2hpZWYtY29sdC05OC5jbGVyay5hY2NvdW50cy5kZXYk"

[[env.preview.r2_buckets]]
binding = 'PUBLIC_BUCKET'
bucket_name = 'noteask-public-preview'

# ------------------------------------------------------------------------------------------------------------

# [env.production]
# logpush = true

[env.production.route]
pattern = "api.noteask.com"
custom_domain = true

[env.production.vars]
WORKER_ENV = "production"
WEB_BASE_URL = "https://app.noteask.com/"
LEMONSQUEEZY_STORE_ID = 71156
LEMONSQUEEZY_PERSONAL_LIFETIME_ACCESS_VARIANT_ID = 258979
LEMONSQUEEZY_TEAM_LIFETIME_ACCESS_VARIANT_ID = 258980
POSTHOG_HOST = "https://us.posthog.com"
POSTHOG_API_KEY = "phc_2Rqwzfz7qYslZPs4Wb8iWLePuNH67jBT0tP1j95snyw"
SUPPORT_EMAIL = "dinsterizer@gmail.com"
CLERK_PUBLISHABLE_KEY = "pk_live_Y2xlcmsubm90ZWFzay5jb20k"

[[env.production.r2_buckets]]
binding = 'PUBLIC_BUCKET'
bucket_name = 'noteask-public-production'

# ------------------------------------------------------------------------------------------------------------
